# Generated by Django 4.2.3 on 2023-07-20 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True, max_length=10, unique=True, verbose_name="Symbol"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=100,
                        verbose_name="Balance",
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="Block Status"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=100, verbose_name="Value"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=100, verbose_name="Fee"
                    ),
                ),
                (
                    "fee_payer",
                    models.CharField(
                        choices=[("system", "System"), ("customer", "Customer")],
                        default="customer",
                        max_length=255,
                        verbose_name="Fee Payer",
                    ),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        decimal_places=4, max_digits=100, verbose_name="Running Balance"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("paid", "Paid"),
                            ("canceled", "Canceled"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="initiated",
                        max_length=255,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("withdraw", "Withdraw"), ("deposit", "Deposit")],
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                (
                    "paid_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Paid DateTime",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="exchange.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
