# Generated by Django 4.2.3 on 2023-07-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("awaiting-payment", "Awaiting Payment"),
                    ("cancel", "Cancel"),
                    ("awaiting-aggregating", "Awaiting Aggregating"),
                    ("in-progress", "In_Progress"),
                    ("done", "Done"),
                    ("unsuccessful", "Unsuccessful"),
                ],
                default="initiated",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
