# Generated by Django 4.2.3 on 2023-07-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0004_alter_order_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ref_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="RefID"
            ),
        ),
    ]
