# Generated by Django 4.2.3 on 2023-07-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0005_order_ref_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=2, verbose_name="Quantity"),
            preserve_default=False,
        ),
    ]
